<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="59053" started-at="2021-10-25T20:04:18 IST" finished-at="2021-10-25T20:05:17 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="59053" started-at="2021-10-25T20:04:18 IST" finished-at="2021-10-25T20:05:17 IST">
      <class name="ExecutionClasses.FullTestSuiteScenario">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:ExecutionClasses.FullTestSuiteScenario@667a738]" name="launchBrowser" is-config="true" duration-ms="11286" started-at="2021-10-25T20:04:18 IST" finished-at="2021-10-25T20:04:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="AdminUserNewWorkOrder()[pri:0, instance:ExecutionClasses.FullTestSuiteScenario@667a738]" name="AdminUserNewWorkOrder" duration-ms="47527" started-at="2021-10-25T20:04:29 IST" finished-at="2021-10-25T20:05:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdminUserNewWorkOrder -->
        <test-method status="FAIL" signature="NurseUserMYWorkOrdersAndRecords()[pri:1, instance:ExecutionClasses.FullTestSuiteScenario@667a738]" name="NurseUserMYWorkOrdersAndRecords" duration-ms="2" started-at="2021-10-25T20:05:17 IST" finished-at="2021-10-25T20:05:17 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at Steps.GoClinical_Nurse_MyWorkOrdersAndRecords_PageSteps.Login(GoClinical_Nurse_MyWorkOrdersAndRecords_PageSteps.java:21)
at ExecutionClasses.FullTestSuiteScenario.NurseUserMYWorkOrdersAndRecords(FullTestSuiteScenario.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NurseUserMYWorkOrdersAndRecords -->
        <test-method status="FAIL" signature="AdminUserSubmitRecords()[pri:2, instance:ExecutionClasses.FullTestSuiteScenario@667a738]" name="AdminUserSubmitRecords" duration-ms="1" started-at="2021-10-25T20:05:17 IST" finished-at="2021-10-25T20:05:17 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at Steps.GoClinical_Admin_Records_PageSteps.Login(GoClinical_Admin_Records_PageSteps.java:19)
at ExecutionClasses.FullTestSuiteScenario.AdminUserSubmitRecords(FullTestSuiteScenario.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdminUserSubmitRecords -->
        <test-method status="PASS" signature="CloseBroswer()[pri:0, instance:ExecutionClasses.FullTestSuiteScenario@667a738]" name="CloseBroswer" is-config="true" duration-ms="203" started-at="2021-10-25T20:05:17 IST" finished-at="2021-10-25T20:05:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBroswer -->
      </class> <!-- ExecutionClasses.FullTestSuiteScenario -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
